version: "2.1"

services:
  server:
    image: painkiller359/asterisk14:latest
    build: .
    container_name: asterisk
    network_mode: host
    ports:
     - 5060:5060/udp
     - 5060:5060/tcp
     - 10000-10050:10000-10050/udp
     - ::5060:5060/tcp
     - ::5060:5060/udp
     - ::10000-10050:10000-10050/udp
    volumes:
     - ./etc/asterisk:/etc/asterisk
    restart: unless-stopped

